### ISSUE TITLE
Failing benchmark metabug

### ISSUE THREAD

**Issue by mdboom** [faster-cpython/benchmarking-public#42]
- [x] 2to3, python_startup, python_startup_nosite: 
  - [x] Needs a [bugfix in pyperf](https://github.com/psf/pyperf/pull/208).  
  - [x] That needs to be [released](https://github.com/psf/pyperf/pull/209)
  - [x] Have pyperformance updated to use it.
- [ ] mypy2: 
  - [x] [New versions of mypy2 are compatible with main by dropping the dependency typed_ast](https://github.com/pyston/python-macrobenchmarks/pull/30).  
  - [x] Need to update to a new version of python_macrobenchmarks
  - [ ] Need to update typing_extensions
- [ ] chameleon:
  - [ ] [Needs upstream changes to support ast module API](https://github.com/malthe/chameleon/issues/430)
- [ ] djangocms:
  - Needs to have libxml2 and libxslt development packages installed on benchmarking machines.
    - [X] linux1
    - [x] linux2
    - [x] arminc
    - [x] macos
    - [ ] windows
  - Needs to have Pillow dependencies installed on the benchmarking machines
    - [x] linux1
    - [x] linux2
    - [ ] arminc
    - [x] macos
    - [ ] windows
- [ ] gunicorn:
  - [x] [multidict needs to be updated](https://github.com/pyston/python-macrobenchmarks/pull/31)
  - [x] Need to update to a new version of python_macrobenchmarks
- [ ] flaskblogging, gunicorn:
  - `Exception: Timeout reached when trying to connect`
- [ ] kinto:
  - [x] Need to [upgrade uWSGI for CPython API changes](https://github.com/pyston/python-macrobenchmarks/pull/32)
  - [x] Need to update to a new version of python_macrobenchmarks
  - [ ] Need to install the CPython build, and not use it from the source directory
- [ ] pytorch_alexnet_inference
  - Lots of problems -- hasn't worked for a long time
- [ ] sqlalchemy (Windows only)
  - The flavor of C++ seems to be incompatible with the compiler
- [ ] tornado
  - `RuntimeError: There is no current event loop in thread 'MainThread'`
